# Generated by Django 5.0.6 on 2024-06-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
